name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build frontend
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd client && npm install && npm run build
      env:
        CI: true
    - name: Build backend
      uses: actions-contrib/go@v0.1.0
    - run: cd server/test/ && go test && cd ../main/ && go build main.go 
